spring:
  datasource:
    username: root
    password: 12345678
    # Mac OS
    url: jdbc:mysql://localhost:3306/wall-bbs?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    # Mac OS
    host: localhost
    port: 6379
    # 没有就不填
    password:

ibaiq:
  # Mac OS
  profile: /Users/lazy/profile/